version: '3'

services:
  myservice:
    build: ./
    volumes:
      - .:/var/www
    ports:
      - 5000:80

  database:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
